### ISSUE TITLE
$headers not used

### ISSUE THREAD

**Issue by FMaz008** [jcleblanc/oauth#1]
In your complete.php file ( for google ), you have:

L. 18    $headers = array("Accept: application/json");
L. 24    $contacts = run_curl($contact_url, 'GET', $headers);

But the 3rd parameter of the run_curl() method is for POST VALUES, and if the 2nd parameter is GET, it will never be used in the execution path.

**Comment by jcleblanc** [comment]
Adjusted in the new OAuth 2 auth push
